/* Generated by scripts/pwa-build.ts at build time. Do not edit. */
'use strict';
const VERSION = "5888412-beb75a5a";
const PRECACHE = [
  "assets/cottage-DocBmdlQ.glb",
  "assets/era1-alehouse-DzKeXhBP.glb",
  "assets/era1-chapel-UMJh9rzD.glb",
  "assets/era1-fisher-hut-D6i_HI-v.glb",
  "assets/era1-hunter-lodge-Dkq4cr4g.glb",
  "assets/era1-market-DV8DNbT8.glb",
  "assets/era1-mine-qx7mMvjw.glb",
  "assets/era1-sawmill-BZw1C1tX.glb",
  "assets/era1-smith-DiiC0YXT.glb",
  "assets/era1-townhall-Dpo1Nio0.glb",
  "assets/era1-watchtower-DG5lcYqp.glb",
  "assets/era1-windmill-0VC2C6Rg.glb",
  "assets/era2-colliery-CJJMMITb.glb",
  "assets/era2-factory-BH43RhXc.glb",
  "assets/era2-warehouse-COPOun0Z.glb",
  "assets/gantari-latin-C8TmYsYu.woff2",
  "assets/gantari-latin-ext-BJnKXFm0.woff2",
  "assets/gantari-latin-ext-italic-DcI_7MTW.woff2",
  "assets/gantari-latin-italic-6lEfw1cM.woff2",
  "assets/index-B4JkSMiv.js",
  "assets/index-DbEvcpCW.css",
  "assets/lora-cyrillic-UWPuZLjM.woff2",
  "assets/lora-cyrillic-ext-YcVxMP-u.woff2",
  "assets/lora-cyrillic-ext-italic-Cgu7qCFu.woff2",
  "assets/lora-cyrillic-italic-BWw7-oF9.woff2",
  "assets/lora-latin-BiLcIKcI.woff2",
  "assets/lora-latin-ext-C2Wlntb9.woff2",
  "assets/lora-latin-ext-italic-BC6VAxdc.woff2",
  "assets/lora-latin-italic-DBI-iqMr.woff2",
  "icons/apple-touch-icon.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/icon-maskable-512.png",
  "icons/icon.svg",
  "index.html",
  "manifest.webmanifest",
  "privacy.html"
];
// The worker sits at the app root, so its own directory is the scope and the
// base every precache path resolves against (root or /last-card-play/ alike).
const ROOT = new URL('./', self.location.href);
// Caches are named by scope as well as version: a root install and a project
// subpath install on one origin share cache storage, and each may only ever
// delete its own generations.
const CACHE_PREFIX = 'last-card:' + ROOT.pathname + ':';
const CACHE = CACHE_PREFIX + VERSION;
const INDEX = new URL('index.html', ROOT).href;
const toKey = (path) => new URL(path, ROOT).href;
const PRECACHED = new Set(PRECACHE.map(toKey));

const withoutQuery = (url) => {
  const u = new URL(url);
  u.search = '';
  u.hash = '';
  return u.href;
};

self.addEventListener('install', (event) => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await Promise.all(PRECACHE.map(async (path) => {
      // Vite hashes everything under assets/, so the HTTP cache may serve
      // those. index.html, the manifest and the icons keep their names: they
      // are fetched past the HTTP cache so a max-age copy of the previous
      // deploy (GitHub Pages sends 600 s) can never seed this version's cache.
      const immutable = path.indexOf('assets/') === 0;
      const request = new Request(toKey(path), { cache: immutable ? 'default' : 'reload', credentials: 'same-origin' });
      const response = await fetch(request);
      if (!response.ok) throw new Error('precache ' + path + ' -> HTTP ' + response.status);
      await cache.put(toKey(path), response);
    }));
    // No skipWaiting(): an installed worker waits for the page's Reload (a
    // SKIP_WAITING message) or for every tab of the old version to close.
  })());
});

self.addEventListener('activate', (event) => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names
      .filter((name) => name.indexOf(CACHE_PREFIX) === 0 && name !== CACHE)
      .map((name) => caches.delete(name)));
    // No clients.claim(): the page that installed the first worker finishes
    // on the network it already loaded from; its next navigation is the first
    // controlled one. A page never changes worker under its feet.
  })());
});

self.addEventListener('message', (event) => {
  const data = event.data;
  if (!data || typeof data !== 'object') return;
  if (data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (data.type === 'GET_VERSION' && event.ports && event.ports[0]) {
    event.ports[0].postMessage({ type: 'VERSION', version: VERSION });
  }
});

async function fromCache(key) {
  const cache = await caches.open(CACHE);
  return cache.match(key);
}

async function cacheFirst(key, request) {
  const hit = await fromCache(key);
  if (hit) return hit;
  // A precached file this cache has lost (storage pressure evicted it) comes
  // from the network and goes back in, so the next offline start is whole.
  const response = await fetch(request);
  if (response.ok) {
    const copy = response.clone();
    caches.open(CACHE).then((cache) => cache.put(key, copy)).catch(() => {});
  }
  return response;
}

async function navigation(request) {
  let key = withoutQuery(request.url);
  if (key === ROOT.href) key = INDEX;
  if (PRECACHED.has(key)) {
    const hit = await fromCache(key);
    if (hit) return hit;
  }
  try {
    return await fetch(request);
  } catch (error) {
    // Offline and not in this cache: an in-scope address still opens the app.
    const shell = await fromCache(INDEX);
    if (shell) return shell;
    throw error;
  }
}

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  if (new URL(request.url).origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith(navigation(request));
    return;
  }
  const key = withoutQuery(request.url);
  if (!PRECACHED.has(key)) return; // version.json, /__build, anything unknown: the network answers
  event.respondWith(cacheFirst(key, request));
});
